name: NDK Build Test (CI)

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      
      - name: Run Bootstrap Script
        shell: bash
        run: |
         sudo apt install -y git unzip ninja-build cmake 
         chmod +x bootstrap.sh
         ./bootstrap.sh
         source ~/.bashrc
        
      - name: Run Build Script
        shell: bash
        run: |
         export PATH=$(pwd)/components/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
         ls
         echo $PATH
         pwd
         echo $(pwd)/components/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin
         make build
